# https://docs.npmjs.com/cli/configuring-npm/package-json
version: 1.0.4
name: "@danielbayley/matchup"
description: Find the first path matching a glob pattern, walking up from a given directory.
keywords:
- find
- find-up
- path
- glob
- pattern
- match
- config
- walk
- traverse

homepage: https://github.com/danielbayley/matchup#readme
repository: danielbayley/matchup
bugs: https://github.com/danielbayley/matchup/issues

author:
  name: Daniel Bayley
  email: daniel.bayley@me.com
  url: https://danielbayley.dev

funding: https://github.com/danielbayley/matchup?sponsor=1
license: MIT

type: module
exports: &index ./index.js
files: [*index]
publishConfig:
  access: public

engines:
  node: ">=20"
  pnpm: ">=10"
packageManager: pnpm@10.0.0

devDependencies:
  fs-fixture: ^2.7.0
  publint: ^0.3.2
  yaml: ^2.7.0

scripts:
  prepare: yaml --single --json --indent ${TABSIZE:-2} < package.yaml > package.json

  test: node --experimental-test-coverage --test test.js

  prerelease: git stash --include-untracked --keep-index && pnpm prepare
  release: pnpm version --force --no-git-tag-version
  postrelease: pnpm publish

  prepublishOnly: publint
  postpublish: git stash pop --quiet

  version: >-
    sed -i "" -E "s/^(version: *)$npm_old_version\$/\\1$npm_new_version/" package.yaml &&
    git commit --message  $npm_new_version package.yaml &&
    git tag    --annotate $npm_new_version --message v$npm_new_version &&
    git push   --follow-tags

  watch: pnpm test --watch
  clean: git clean -X --force
  zap: pnpm clean && rm -rf node_modules || true
  reinstall: pnpm zap && pnpm install
